### ISSUE TITLE
Auto-generate Xcode project to reduce merge conflicts

### ISSUE THREAD

**Issue by wtimme** [bryceco/GoMap#450]
> As a developer, I want the Xcode project to be auto-generated from the file structure on the disk, so that I run into less merge conflicts for the project file

## Motivation

Renamings and a change in the file structure (e. g. the addition of new icons and files) can cause merge conflicts in the Xcode project file.

Resolving these merge conflicts can be a bit of a pain, and may cause mistakes being made.

## Proposed solution

I propose we make use of [XcodeGen][1]. We create a `project.yml` file in the root directory of the repository that allows for the automatic (re-) generation of the `.xcodeproj` file. If merge conflicts occurred, one could simply run `xcodegen generate` to re-generate the project file and commit the newly generated file

XcodeGen uses the file structure on disk to generate groups, allowing for an easy renaming/addition of files. It removes the need to manually sort the files by name. In addition, adding new targets as getting easier as well.

[1]: https://github.com/yonaskolb/XcodeGen

**Comment by bryceco** [comment]
Rather than always using XcodeGen couldn't we have it as an optional solution used only when merge conflicts occur? That way if people want to use it they can, or if they prefer to use the project file that is pre-built they can.￼

**Comment by 1ec5** [comment]
Merge conflicts almost always occur in .pbxproj files because of files being added in the same group by two different commits. Supposedly a [union merge strategy](https://about.gitlab.com/blog/2015/02/10/gitlab-reduced-merge-conflicts-by-90-percent-with-changelog-placeholders/) helps with files that usually conflict this way (also running changelogs). If something like that works, then keeping the checked-in Xcode project would keep the development environment straightforward for new contributors to set up.

**Comment by bryceco** [comment]
That's great info, thanks! I also prefer a solution that supports "download/open in Xcode/build" without any additional steps. But I'm fine with adding a .yml for those situations where git merge has problems.

**Comment by wtimme** [comment]
I did some testing with XcodeGen. Here is the content for a `project.yml` that will allow for the main app and both test targets to run:

```yml
name: GoMap
options:
  bundleIdPrefix: com.bryceco
targets:
  GoMap:
    type: application
    platform: iOS
    deploymentTarget: "9.0"
    scheme:
      testTargets:
        - GoMapTests
    sources:
      - path: src/Shared
      - path: src/iOS
        excludes:
          - "*.xcodeproj"
          - ".gitignore"
          - "Gemfile*"
          - GoMapTests
          - GoMapUITests
          - "Go Map!!-Info.plist"
      - path: src/Images.xcassets
      - path: src/POI-Icons/POI-Icons.xcassets
      - path: src/presets
        buildPhase: resources
        type: folder
    settings:
      base:
        INFOPLIST_FILE: "src/iOS/Go Map!!-Info.plist"
        SWIFT_OBJC_BRIDGING_HEADER: "src/iOS/Go Map!!-Bridging-Header.h"
        GCC_PREFIX_HEADER: "src/iOS/Go Map!!-Prefix.pch"
        SWIFT_OBJC_INTERFACE_HEADER_NAME: "$(SWIFT_MODULE_NAME)-Swift.h"
        PRODUCT_MODULE_NAME: "Go_Map__"
  GoMapTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "9.0"
    sources:
      - path: src/iOS/GoMapTests
    dependencies:
      - target: GoMap
  GoMapUITests:
    type: bundle.ui-testing
    platform: iOS
    deploymentTarget: "9.0"
    scheme:
      testTargets:
        - GoMapUITests
    sources:
      - path: src/iOS/GoMapUITests
    dependencies:
      - target: GoMap
```

To be perfectly honest, I haven't tested the whole application, and I haven't tested Beta deployment to TestFlight. But it's a start, and it gives you an idea of what such a configuration file would look like.
